### ISSUE TITLE
Make RL tutorial

### ISSUE THREAD

**Issue by c3n0te** [SENG-499-Company-3/algorithm-1#6]
Provide interactive resources to get developers comfortable with the reinforcement learning workflow.

**Comment by seiyaterada** [comment]
I've looked at some tutorials online and was able to narrow down to 3 tutorials which I thought would be useful to learning about reinforcement learning and the technologies we will be using.

1. [Learning to play Pong](https://docs.ray.io/en/latest/ray-core/examples/plot_pong_example.html)

- Tutorial created by Ray
- Example using Ray and Gym to create a neural network to play Pong


2. [Intro to Rllib](https://medium.com/distributed-computing-with-ray/intro-to-rllib-example-environments-3a113f532c70)

- This one uses Rllib by Ray, Gym, and Tensorflow
- Starts with an introduction to reinforcement learning
- Has multiple examples to work through

3. [Intro to Reinforcement Learning](https://www.anyscale.com/blog/an-introduction-to-reinforcement-learning-with-openai-gym-rllib-and-google)

- Also goes over what reinforcement learning is
- Uses Gym Cartpole environment
- How to train agents using Rllib
- Using GPU to speed of training
- Hyperparameter tuning with Ray Tune

I personally think the 3rd one is really good as it covers most of the tools we will be using as well as explain some of the concepts in reinforcement learning while walking through examples

**Comment by ianmclaren** [comment]
Finished Tutorial 3. Ran into some issues with the tutorial due to a combination of working on windows and VS Code, plus having Python 3.11, which doesn't have compatibility with Ray. I found using Google colab was the easiest way to circumvent the issues. Will start on Tutorial 1 next and try it with Jupyterhub.
